resumeproject/urls.py
from django.contrib import admin
from django.urls import path,include
from resumeapp import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.resumeviews, name='home'),
    path('<int:pk>', views.resumedetailviews,name='detail')
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

resumeapp/models.py
from django.db import models

# Create your models here.
STATE_CHOICE = (
('punjab','punjab'), 
('KPK','KPK'),
('Gilgit','Gilgit'),
('Sind','Sind'),
('Balochistan','Balochistan'))
class Resumemodel(models.Model):
    name = models.CharField(max_length=200)
    father_name = models.CharField(max_length=200)
    dob = models.DateField(auto_now_add=False, auto_now=False)
    education = models.CharField(max_length=200)
    gender = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    pin = models.PositiveIntegerField()
    locality = models.CharField(max_length=200)
    state = models.CharField(choices=STATE_CHOICE ,max_length=50)
    mobile = models.PositiveIntegerField()
    email = models.EmailField()
    job_city = models.CharField(max_length=200)
    profile_img = models.ImageField(upload_to='profile_img',blank=True)
    my_file = models.FileField(upload_to="CV", blank=True)

resumeapp/forms.py
from django import forms
from .models import Resumemodel

GENDER_CHOICES =[
    ('Male','Male'),
    ('Female','Female')
]

CITY_JOB_CHOICES = [('Lahore','Lahore'),('Faisalabad','Faisalabad'),
('Karachi','Karachi'),('Multan','Multan'),('Islamabad','Islamabad')]

class Resumeform(forms.ModelForm):
    gender = forms.ChoiceField(choices=GENDER_CHOICES, widget=forms.RadioSelect)
    job_city = forms.MultipleChoiceField(label='Preferred Job City', choices=CITY_JOB_CHOICES , widget=forms.CheckboxSelectMultiple)
    class Meta:
        model = Resumemodel
        fields = '__all__'
        labels = {'name':'Full Name','father_name':'Father Name','dob':'Date Of Birth','education':'Education','gender':'Gender','city':'Your City',
        'pin':'Postal Code','locality':'Locality','state':'State','mobile':'Mobile Number','email':'Email Address','job_city':'Prefer Job City'}
        error_messages = {'name':{'required':'please enter name'}, 'father name':{'required':'Please Enter Father Name'},'dob':{'required':'Enter Date of Birth'},'education':{'required':'Please Enter Education'},'mobile':{'required':'Please Enter Mobile Number'}}
        widgets = {'name':forms.TextInput(attrs={'class' : 'form-control','placeholder':'Your Name'}),
        'father_name':forms.TextInput(attrs={'class' : 'form-control','placeholder':'Your Father'}),
        'dob':forms.DateInput(attrs={'class' : 'form-control','id':'datepicker','placeholder':'Your Date Of Birth'}),
        'education':forms.TextInput(attrs={'class' : 'form-control','placeholder':'Your Education'}),
        'city':forms.TextInput(attrs={'class' : 'form-control','placeholder':'Current City'}),
        'pin':forms.NumberInput(attrs={'class' : 'form-control','placeholder':'Enter Postal Code Ex # 32500'}),
        'locality':forms.TextInput(attrs={'class' : 'form-control','placeholder':'Enter Distric'}),
        'state':forms.Select(attrs={'class' : 'form-select'}),
        'mobile':forms.NumberInput(attrs={'class' : 'form-control','placeholder':'Mobile Number With Country Code'}),
        'email':forms.EmailInput(attrs={'class' : 'form-control','placeholder':'For Example # example@gmail.com'}),
        }

    def clean(self):
        cleaned_data = super().clean()
        valname = self.cleaned_data['name']
        valfname = self.cleaned_data['father_name']
        if len(valname)<5:
            raise forms.ValidationError("Name should be minimum 5 character long")

        if len(valfname)<5:
            raise forms.ValidationError("Father Name should be minimum 5 character long")    

resumeapp/views.py
from django.shortcuts import render,HttpResponseRedirect
from .forms import  Resumeform
from .models import Resumemodel
# Create your views here.
def resumeviews(request):
    if request.method=="POST":
        fm = Resumeform(request.POST,request.FILES)
        if fm.is_valid():
            fm.save()
            return HttpResponseRedirect('/')

    else:
        fm = Resumeform()
    stu = Resumemodel.objects.all()          
    return render(request, 'home.html',{'form':fm,'candidates':stu})

def resumedetailviews(request,pk):
    stu = Resumemodel.objects.get(pk=pk)
    return render(request, 'detail_resume.html',{'candidatedetail':stu})

templates/detail_resume.html
<!doctype html> {% load myfilter %}
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Resume Detail Page</title>
</head>

<body>
    <div class="container">
        <h1 class="text-center text-danger mb-5 bg-dark p-4"> Candidate Resume Detail </h1>
        <div class="row">
            <div class="col-sm-10 shadow p-5 offset-sm-1">
                <p class="float-end">Candidate No : {{candidatedetail.id}}</p>
                <img src="{{detail.profile_img.url}}" class="float-end img-fluid img-thumbnail mt-4" width="150" height="150">
                <p>Name of Candidate : {{candidatedetail.name}}</p>
                <p>Address : {{candidatedetail.city}} {{candidatedetail.locality}} {{candidatedetail.state}}</p>
                <p>Mobile Number : {{candidatedetail.mobile}}</p>
                <p>Job City : {{candidatedetail.job_city|remove_special:"[]'"}}</p>
                <p>Email Address : {{candidatedetail.email}}</p>
                <p>CV :
                    <a href="{{detail.my_file.url}}">Download</a>
                </p>
                <div class="text-center ">
                    <a href="/" class="btn btn-primary">Back To Home</a></div>
            </div>
        </div>
    </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
</body>

</html>

templates/home.html
<!doctype html> {% load static %}
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.13.0/themes/base/jquery-ui.css">
    <title>Home</title>
    <style>
        #id_gender,
        #id_job_city {
            list-style: none;
            display: inline-flex;
        }
        
        #id_gender>li,
        #id_job_city>li {
            padding-left: 10px;
        }
    </style>
    <link rel="stylesheet" href="{% static 'css/all.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Satisfy&display=swap" rel="stylesheet">
</head>

<body>

    <div class="container mb-5">
        <h1 class="text-center text-secondary bg-dark p-3">Candidate Resume </h1>
        <div class="row">
            <div class="col-sm-8">
                <form action="" method="POST" enctype="multipart/form-data" class="shadow p-5" novalidate>{% csrf_token %}{{form.as_p}}<input type=submit value="Submit" class="btn btn-primary"></form>
            </div>
            <div class="col-sm-4 text-center mt-5">
                <h4> <u>List Of Candidate</u></h4> {% for candidate in candidates%} {{candidate.id}} :
                <a href="{% url 'detail' candidate.id %}">{{candidate.name}}</a>

                <hr>{% endfor %}
            </div>
        </div>
    </div>


    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
    <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
    <script src="https://code.jquery.com/ui/1.13.0/jquery-ui.js"></script>
    <script src="{% static 'core/js/jquery.js'%}">
    </script>
    <script src="{% static 'js/popper.js'%}">
    </script>
    <script src="{% static 'js/all.min.js'%}">
    </script>
    <script src="{% static 'js/bootstrap.min.js'%}">
    </script>
    <script>
        $(function() {
            $("#datepicker").datepicker();
            $("#anim").on("change", function() {
                $("#datepicker").datepicker("option", "showAnim", $(this).val());
            });
        });
    </script>
</body>

</html>